# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :node1cos8p, primary: true do |node1|
    node1.vm.box = "centos/8"
    node1.vm.hostname = "mysql8-cos8-node1"
    node1.vm.box_version = "1905.1"
    node1.vm.network "private_network", ip: "192.168.88.22"
    node1.vm.network "private_network", ip: "fc00::1:122"
    node1.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
    node1.vm.provision :shell do |shell|
      shell.path = "provision.sh"
      shell.args = ["primary"]
    end
  end
  config.vm.define :node2cos8s do |node2|
    node2.vm.box = "centos/8"
    node2.vm.hostname = "mysql8-cos8-node2"
    node2.vm.box_version = "1905.1"
    node2.vm.network "private_network", ip: "192.168.88.24"
    node2.vm.network "private_network", ip: "fc00::1:124"
    node2.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
    node2.vm.provision :shell do |shell|
      shell.path = "provision.sh"
      shell.args = ["secondary"]
    end
  end
  config.vm.define :node3cos8r do |node3|
    node3.vm.box = "centos/8"
    node3.vm.hostname = "mysql8-cos8-node3"
    node3.vm.box_version = "1905.1"
    node3.vm.network "private_network", ip: "192.168.88.28"
    node3.vm.network "private_network", ip: "fc00::1:128"
    node3.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
    node3.vm.provision :shell do |shell|
      shell.path = "provision.sh"
      shell.args = ["router"]
    end
    config.vm.provision "file", source: "./innodb-cluster-status.js", destination: "/tmp/innodb-cluster-status.js"
  end
end
