# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define :node1cos8cdb3, primary: true do |node1|
    node1.vm.box = "centos/8"
    config.vm.box_url = "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20201019.1.x86_64.vagrant-virtualbox.box"
    node1.vm.hostname = "cos8cdb3node1"
    # node1.vm.box_version = "1905.1"
    node1.vm.network "private_network", ip: "192.168.83.86"
    node1.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
    node1.vm.provision :shell do |shell|
      shell.path = "provision.sh"
      shell.args = ["define-first"]
    end
  end
  config.vm.define :node2cos8cdb3 do |node2|
    node2.vm.box = "centos/8"
    config.vm.box_url = "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20201019.1.x86_64.vagrant-virtualbox.box"
    node2.vm.hostname = "cos8cdb3node2"
    # node2.vm.box_version = "1905.1"
    node2.vm.network "private_network", ip: "192.168.83.89"
    node2.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
    node2.vm.provision :shell do |shell|
      shell.path = "provision.sh"
      shell.args = ["define-second"]
    end
  end
  #config.vm.provision "file", source: "./local.ini",   destination: "/tmp/local.ini"
  #config.vm.provision "file", source: "./default.ini", destination: "/tmp/default.ini"

end
